name: Script Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install ShellCheck
        run: sudo apt install shellcheck -y

      - name: Check Script
        run: shellcheck install.sh
